### ISSUE TITLE
QC - Project Workspace - Tasks Tab: the status is In progress but it should be not started when the start date is in future

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#63]
Steps: 

1. login as epmadmin 
2. open http://rmpplus-qc.masterteam.sa/#/project/a4c99f6b-4ab1-489c-8793-23b11e49f93c/tasks/
3. check task2 status and start date 

Actual Result: 
the status is In progress but it should be not started as the start date is in 5 Dec 

![image](https://user-images.githubusercontent.com/110157969/201513025-9a2b4bdd-c5d5-414d-9912-2426a80f45d1.png)

**Comment by JarrarMo** [comment]
@DemaHamideh status is based on baseline start date which is September 30.

**Comment by DemaHamideh** [comment]
@JarrarMo check now please, it is 5 Dec 

http://94.127.212.109:2022/PWA/Project%20Detail%20Pages/Schedule.aspx?ProjUid=a4c99f6b-4ab1-489c-8793-23b11e49f93c&ret=0

![image](https://user-images.githubusercontent.com/110157969/201513899-4a2f91d8-fefd-40ac-8184-8c712a4e731b.png)

**Comment by JarrarMo** [comment]
@DemaHamideh Please make sure build a right plan structure in order to get the right outcome, there should be a root for tasks which will have the project name, also you should set a baseline after you finish your task building, the project baseline available at schedule will be the baseline available at p+
If there was not root task, EPM will calculate based on the first task which was September 30
![image](https://user-images.githubusercontent.com/53216161/201514695-3688b19f-8640-4d8d-bd9b-95d577813ba1.png)
![image](https://user-images.githubusercontent.com/53216161/201514760-3e46d282-c443-4e68-8770-3fa1ef9b37cd.png)

**Comment by JarrarMo** [comment]
@DemaHamideh sorry for inconvenience, I thought you are talking about the project itself, will check this with FE

@saqratieh fyi

**Comment by ealtiti** [comment]
<img width="1006" alt="Screen Shot 2022-11-13 at 3 24 41 PM" src="https://user-images.githubusercontent.com/85454412/201521528-ba9c1e6b-ccf8-4bcb-8dcd-b7ff7478c0ad.png">
