### ISSUE TITLE
New projects are not added to epm and not shown in P+ 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#72]
Steps:

1. login as epmadmin
2. click on create new project 
3. fill all the data and click on submit

Actual Result: 
the project is not created and I can't find it in epm 

![test st](https://user-images.githubusercontent.com/110157969/203296379-e5c07d82-87d5-49ca-9e99-1be70ed4b4cf.PNG)

![image](https://user-images.githubusercontent.com/110157969/203296489-ff56c9a9-bb77-4610-bb08-3f66216264e6.png)

after waiting the sync 
![image](https://user-images.githubusercontent.com/110157969/203296556-2e9fdc04-6a57-476e-ad40-11066315824f.png)

+++ 

if I try to add it again with the same name, P+ will show that this name is already exist 

![test st duplicate](https://user-images.githubusercontent.com/110157969/203296645-4db9071c-185b-488d-8b73-f7fd1911b9c8.png)

**Comment by JarrarMo** [comment]
@DemaHamideh I've created a new project and its showing, server was throwing timeout error, I increased it
![image](https://user-images.githubusercontent.com/53216161/203301395-242c7022-52c6-4799-9063-ea9295b84d20.png)
![image](https://user-images.githubusercontent.com/53216161/203301417-37fe69c3-10f2-4509-9acc-5ae5d9ec5ff9.png)

For the second point, we will check if there is a request with the same project name and check EPM in the same time, its not on EPM but still exists as request, that's why you could not add the same name

**Comment by DemaHamideh** [comment]
Fixed now and added correctly
